---
title: "p8105_hw3_sl5009"
author: "Shengzhi Luo"
date: "15/10/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1

```{r}
library(p8105.datasets)
data("instacart")
```

```{r,message=FALSE}
library(tidyverse)
library(dplyr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
How many aisles are there, and which aisles are the most items ordered from?

```{r}
instacart %>%
  group_by(aisle_id) %>% 
  summarise(n_obs=n()) %>% 
  arrange(desc(n_obs))
```
As from the above table, we can see there are 134 aisles in total and the most items ordered from aisle_id 83.


```{r}
instacart %>%
  group_by(aisle_id) %>% 
  summarise(n_obs=n()) %>% 
  filter(n_obs>10000) %>% 
  ggplot(aes(x = aisle_id, y = n_obs, color = aisle_id)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```


